# Generated by Django 3.2.3 on 2021-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('e', 'English'), ('m', 'Mandarin'), ('j', 'Japanese')], default='e', help_text='Language', max_length=1),
        ),
    ]
